### ISSUE TITLE
Prepare OPAL for Java 20

### ISSUE THREAD

**Issue by errt** [stg-tud/opal#115]
There are a few changes to the [JVM specification](https://cr.openjdk.org/~iris/se/20/latestSpec/java-se-20-jvms-fr-diffs.pdf) that may warrant a closer look. They are on pages 24, 25, 403, and 404 and concern threads, uncaught exception handling, and thread/VM termination.
I believe these changes to be mostly clarifications of existing behavior instead of actual changes, but we should nonetheless have a look at whether we correctly model this behavior, e.g., in abstract interpretation and call graphs. In particular, we might not yet correctly handle the invocation of uncaughtException on ThreadGroups and the default handler.

**Comment by JuliusNmn** [comment]
[143](https://github.com/opalj/opal/pull/143)
