### ISSUE TITLE
Compiling the java test fixture failed

### ISSUE THREAD

**Issue by mohPYdev** [stg-tud/opal#147]
I encountered a compilation error while trying to build the project. Here are the details:

environment: 
- Java 11
- SBT 1.6.2  (increased heap size to 12GB)
- Scala 2.12.15

I followed the instructions mentioned in your README file. the result of " sbt cleanBuild" is the following error:

[log.txt](https://github.com/opalj/opal/files/12842145/log.txt)

Error message:
Compiling the java test fixture failed

**Comment by errt** [comment]
From your log, it is clear that Java 16 is now required to build the test fixtures. We will update the readme accordingly. Thanks for reporting.

Note that we are also using Scala 2.13(.11) now, but that should not be a problem as sbt should download the correct version automatically.

**Comment by tillbecks** [comment]
I encounter the same issue using Java 17, sbt 1.10.(1) and Scala 2.13.15.

**Comment by errt** [comment]
@tillbecks Can you provide your console output?

**Comment by tillbecks** [comment]
Yes of course:
[log.txt](https://github.com/user-attachments/files/17658949/log.txt)

**Comment by errt** [comment]
Your problem seems to be the spaces in your directory path. I can't easily see what encoding the Eclipse BatchCompiler would accept, but you could try replacing the `toString` in line 96 (and probably the implicit one in line 101) of `org.opalj.javacompilation.FixtureCompileSpec` with `toURI`

**Comment by tillbecks** [comment]
Just changing the path did the job for me! Thank you so much

**Comment by errt** [comment]
I thought so, but I would value a pull request to fix the FixtureCompiler not working with paths containing spaces, it is still a bug after all.
