### ISSUE TITLE
Add requiredProjectInformationKeys to EntryPointFinder

### ISSUE THREAD

**Issue by JuliusNmn** [stg-tud/opal#223]
Instead of a doc comment on this, we should extend EntryPointFinder to have a method for requiredProjectInformationKeys, override this here to specify the AndroidManifestKey and then use that method in the InitialEntryPointKey to compute the correct set of required keys. That will need some rewriting of the InitialEntryPoints key to get the used EntryPointsFinder earlier though.

_Originally posted by @errt in https://github.com/opalj/opal/pull/222#discussion_r1806299022_

**Comment by errt** [comment]
Fixed by #244
