### ISSUE TITLE
processing BAT-Demo failed

### ISSUE THREAD

**Issue by tillbecks** [stg-tud/opal#233]
After building OPAL and trying out some Demos, I encountered an Error that appears on some of the demos (around Demo 48).
This is the output of the console when trying out Demo 48:
[log](https://github.com/user-attachments/files/17702804/sbt.output.log)

I couldn't figure out what the problem is. It might be due to spaces or other special characters in the path, like in another issue I commented on.

Thanks in advance.

**Comment by errt** [comment]
Yes, it is obviously the space in the directory structure inside bugs.zip. PR for fix issued.
